In [1]:
# Import librerie
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import my_dataset_frame
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn import svm


In [2]:
dataset = my_dataset_frame.load_my_dataset()

In [3]:
clf = svm.SVC(gamma=0.001, C=100.)


In [37]:
c = (255*(dataset.data[0] - np.min(dataset.data[0]))/np.ptp(dataset.data[0])).astype(int)        


In [39]:
print(c)
print(dataset.data[0])

[ 57 113 147 179 217 255 217 173 141 104  52  23 110 147 176 234 176 144
 107  55  89 121 159 197 159 115  84  46   5  34  52  89 118 176 118  86
  49  34  66 104 141 104  60  28   8  60  89   2  34  63 121  63  31   5
  31  69 107  69  26   5  43  95 124  37   0  28  86  28   2  40  37  75
  37   5  37  75 127 156  69  31   2  55   2  34  72  37   0  43  75 113
 165 194 107  69  40  17  40  72 110  37  81 113 150 202 231 144 107  78
  20  78 110 147  43  75 113 165 194 107  69  40  17  40  72 110  31  69
 121 150  63  26   2  60   2  28  66  37  89 118  31   5  34  92  34   2
  34  52  81   5  43  72 130  72  40   2  28  57  95 124 182 124  92  55
  86 124 153 211 153 121  84  37  66 124  66  34   2  28  86  28   2  40
  57   0  31  69  57  89 127  31  69  37]
[20.0 39.0 51.0 62.0 75.0 88.0 75.0 60.0 49.0 36.0 18.0 8.0 38.0 51.0 61.0
 81.0 61.0 50.0 37.0 19.0 31.0 42.0 55.0 68.0 55.0 40.0 29.0 16.0 2.0 12.0
 18.0 31.0 41.0 61.0 41.0 30.0 17.0 12.0 23.0 36.0 49.0 36.0 21.0 10.0 3.0
 21

In [5]:
dataset.data

array([[20.0, 39.0, 51.0, ..., 11.0, 24.0, 13.0],
       [20.0, 39.0, 51.0, ..., 11.0, 24.0, 13.0],
       [21.0, 40.0, 51.0, ..., 12.0, 24.0, 12.0],
       ...,
       [7.0, 15.0, 22.0, ..., 7.0, 14.0, 7.0],
       [7.0, 16.0, 22.0, ..., 7.0, 14.0, 7.0],
       [8.0, 17.0, 24.0, ..., 7.0, 14.0, 7.0]], dtype=object)

In [6]:
dataset.target.shape

(1996,)

In [7]:
dataset.target

array([1, 1, 1, ..., 4, 4, 4])

In [8]:
clf.fit(dataset.data,dataset.target)

SVC(C=100.0, gamma=0.001)

In [9]:
df=pd.read_csv('/Users/paone/Desktop/csv_computati/4_1_1_4_30_37.csv', sep=',',header=None)

In [10]:
a = clf.predict(df)

In [11]:
a

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,

In [12]:
ylist = []
for val in a:
    ylist.append(4)
y = np.array(ylist)

In [13]:
from sklearn.metrics import accuracy_score


In [14]:
y.shape

(450,)

In [15]:
a.shape

(450,)

In [16]:
print(accuracy_score(y, a))

1.0


In [17]:
type(a)

numpy.ndarray

In [18]:
tot4, tot3, tot2, tot1 = 0, 0, 0, 0
for val in a:
    if(val==4):
        tot4 +=1
    elif(val==3):
        tot3 +=1
    elif(val==2):
        tot2 +=1
    elif(val==1):
        tot1 +=1

In [19]:
print("tot di 4 : " + str(tot4))
print("tot di 3 : " + str(tot3))
print("tot di 2 : " + str(tot2))
print("tot di 1 : " + str(tot1))

tot di 4 : 450
tot di 3 : 0
tot di 2 : 0
tot di 1 : 0
