In [1]:
# Import librerie
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import produce_pca_files
import my_dataset
#import my_dataset_norm
#import my_dataset_norm2
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import csv
from sklearn.utils import Bunch
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV



In [2]:
#dataset = produce_pca_files.load_dataset()   #con riduzione pca
dataset = my_dataset.load_dataset()           #senza normalizzazione  
#dataset = my_dataset_norm.load_dataset()     #con normalizzazione  
#datasetN = my_dataset_norm2.load_dataset()    #con nuova normalizzazione

In [3]:
print(dataset.data.shape)
print(dataset.target.shape)

(300, 23100)
(300,)


In [4]:
print(dataset.data)

[[37.0 70.0 92.0 ... 19.0 50.0 31.0]
 [30.0 57.0 68.0 ... 20.0 41.0 23.0]
 [39.0 80.0 114.0 ... 36.0 83.0 50.0]
 ...
 [47.0 85.0 117.0 ... 39.0 74.0 38.0]
 [36.0 75.0 95.0 ... 27.0 64.0 37.0]
 [48.0 87.0 108.0 ... 30.0 73.0 43.0]]


In [5]:
dataset.target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [6]:

'''path = "D:/test_set"
MAX_LINES = 350
def carica_test_set():
    """
    Questo metodo restutuisce il dataset non normalizzato
    """
    dataset = []
    targets = []
    for file in os.listdir(path):     #per ogni file video nella cartella
        data = []
        line_count = 1
        with open(path + "/" + file) as csv_file:           #apre il file csv
            csv_reader = csv.reader(csv_file, delimiter=',')
            for row in csv_reader:
                if(line_count <= MAX_LINES):        #Inserisce MAX_LINES righe nel dataset
                    new_row = [float(i) for i in row]       #Converte in float i valori del file csv
                    for element in new_row:
                        data.append(element)            #Aggiunge tutti i valori allo stesso array in modo da avere nel Dataset ogni riga (NumpyArray) rappresenti un file csv
                    line_count+=1
            dataset.append(np.array(data))                  
            targets.append(int(file.split('_')[0]))     #Aggiunge il primo valore del nome come etichetta
    np_targets = np.array(targets)              #Converte in numpy array
    np_dataset = np.array(dataset, dtype=object)        #Converte in numpyarray
    return Bunch(data = np_dataset, target = np_targets)
'''

In [109]:
x_train, x_test, y_train, y_test = train_test_split(dataset.data,dataset.target, test_size=0.3)

In [110]:
y_train.size

210

In [41]:
#test_set = carica_test_set()

In [42]:
#test_set.data.shape

(0,)

In [11]:
#test_set.data

array([[39.0, 80.0, 114.0, ..., 36.0, 83.0, 50.0],
       [43.0, 83.0, 114.0, ..., 35.0, 81.0, 46.0],
       [34.0, 59.0, 85.0, ..., 33.0, 79.0, 49.0],
       ...,
       [31.0, 67.0, 94.0, ..., 28.0, 68.0, 41.0],
       [37.0, 77.0, 99.0, ..., 23.0, 65.0, 41.0],
       [43.0, 79.0, 104.0, ..., 31.0, 69.0, 39.0]], dtype=object)

In [12]:
#test_set.target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [111]:
y_test

array([4, 4, 1, 1, 4, 4, 1, 2, 3, 3, 2, 3, 2, 2, 2, 3, 1, 4, 1, 4, 2, 4,
       1, 1, 1, 4, 2, 1, 2, 2, 2, 3, 3, 3, 4, 2, 2, 3, 3, 4, 1, 1, 2, 1,
       3, 3, 3, 3, 3, 4, 2, 1, 4, 3, 2, 1, 4, 4, 4, 2, 1, 3, 1, 3, 3, 1,
       2, 3, 2, 1, 1, 3, 1, 4, 4, 3, 4, 2, 2, 2, 2, 4, 1, 1, 3, 1, 4, 3,
       4, 2])

In [152]:
 # // indice prova /// con 33 pca
#classifier = svm.SVC() #  a support vector classifier
#classifier = KNeighborsClassifier(1)  
#classifier = SVC(kernel="linear", C=0.025) 
#classifier = SVC(gamma=2, C=1) 
#classifier = GaussianProcessClassifier()  
#classifier = DecisionTreeClassifier(random_state= 0)   #criterion = "entropy"
#classifier = RandomForestClassifier(random_state = 0)     #or 5 e 10 e 1
#classifier = MLPClassifier(alpha=1, max_iter=1000) 
classifier = AdaBoostClassifier()
#classifier = GaussianNB()  
#classifier = QuadraticDiscriminantAnalysis() 
#classifier = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
#classifier = BaggingClassifier(KNeighborsClassifier(), max_samples=0.5, max_features=0.5)

In [153]:
classifier.fit(x_train,y_train)
#classifier.fit(dataset.data,dataset.target)

AdaBoostClassifier()

In [154]:
predicted = classifier.predict(x_test)
#predicted = classifier.predict(test_set.data)

In [155]:
accuracy_score(predicted,y_test)
#accuracy_score(predicted,test_set.target)

0.3111111111111111

In [33]:
parameters = {'n_neighbors':[1,2,3,4,5]}

In [34]:
clf = GridSearchCV(classifier, parameters)


In [35]:
clf.fit(dataset.data,dataset.target)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5]})

In [37]:
clf.cv_results_

{'mean_fit_time': array([0.13974171, 0.1352458 , 0.13710656, 0.13103657, 0.13080382]),
 'std_fit_time': array([0.01794109, 0.02277351, 0.01114527, 0.00906619, 0.01510779]),
 'mean_score_time': array([0.04038877, 0.04506612, 0.04038053, 0.04607   , 0.04802904]),
 'std_score_time': array([0.00351283, 0.00385656, 0.00184188, 0.00323517, 0.00659032]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5}],
 'split0_test_score': array([0.1509434 , 0.16981132, 0.16981132, 0.18867925, 0.20754717]),
 'split1_test_score': array([0.43396226, 0.47169811, 0.43396226, 0.37735849, 0.37735849]),
 'split2_test_score': array([0.32075472, 0.33962264, 0.33962264, 0.39622642, 0.39622642]),
 'split3_test_score': array([0.37735849, 0.35849057, 0.33962264, 0.28301887, 0.37735849]),


In [119]:
clf.best_score_

0.32452830188679244

In [21]:
predicted = clf.predict(test_set.data)

In [22]:
accuracy_score(predicted,test_set.target)

0.25

In [23]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_n_neighbors',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [24]:
from sklearn.metrics import plot_confusion_matrix

In [25]:
titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(classifier, x_test, y_test,
                                 cmap=plt.cm.Blues,
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()

NameError: name 'x_test' is not defined