In [43]:
# Import librerie
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import my_dataset_frame
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn import svm


In [46]:
dataset = my_dataset_frame.load_my_dataset()

In [47]:
clf = svm.SVC(gamma=0.001, C=100.)


In [48]:
dataset.data.shape

(1546, 190)

In [49]:
dataset.data

array([[20.0, 39.0, 51.0, ..., 11.0, 24.0, 13.0],
       [20.0, 39.0, 51.0, ..., 11.0, 24.0, 13.0],
       [21.0, 40.0, 51.0, ..., 12.0, 24.0, 12.0],
       ...,
       [7.0, 15.0, 22.0, ..., 7.0, 14.0, 7.0],
       [7.0, 16.0, 22.0, ..., 7.0, 14.0, 7.0],
       [8.0, 17.0, 24.0, ..., 7.0, 14.0, 7.0]], dtype=object)

In [50]:
dataset.target.shape

(1546,)

In [51]:
dataset.target

array([1, 1, 1, ..., 4, 4, 4])

In [62]:
clf.fit(dataset.data,dataset.target)

SVC(C=100.0, gamma=0.001)

In [59]:
df=pd.read_csv('/Users/paone/Desktop/csv_computati/4_1_1_4_30_37.csv', sep=',',header=None)

In [65]:
a = clf.predict(df)

In [66]:
a

array([4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 3, 4, 3, 4, 3, 4, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4,
       4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 4, 4, 4, 4, 3,
       3, 3, 3, 3, 4, 4, 2, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 4, 4, 2, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3,
       3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4,
       3, 4, 3, 4, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 2, 2,
       4, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 3, 2,

In [90]:
ylist = []
for val in a:
    ylist.append(4)
y = np.array(ylist)

In [94]:
from sklearn.metrics import accuracy_score


In [95]:
y.shape

(450,)

In [96]:
a.shape

(450,)

In [97]:
print(accuracy_score(y, a))

0.5111111111111111


In [68]:
type(a)

numpy.ndarray

In [75]:
tot4, tot3, tot2, tot1 = 0, 0, 0, 0
for val in a:
    if(val==4):
        tot4 +=1
    elif(val==3):
        tot3 +=1
    elif(val==2):
        tot2 +=1
    elif(val==1):
        tot1 +=1

In [77]:
print("tot di 4 : " + str(tot4))
print("tot di 3 : " + str(tot3))
print("tot di 2 : " + str(tot2))
print("tot di 1 : " + str(tot1))

tot di 4 : 230
tot di 3 : 113
tot di 2 : 107
tot di 1 : 0
